#CONTIKI = /home/user/contiki-2.6/

ifndef TARGET
TARGET=sky
endif

CONTIKI_PROJECT = test-DS1000
CONTIKI_SOURCEFILES += ds1000-sensor.c
all: $(CONTIKI_PROJECT)



include $(CONTIKI)/Makefile.include
