#CONTIKI = /home/user/contiki-2.6/

ifndef TARGET
TARGET=xm1000
endif

CONTIKI_PROJECT = ds1000-test
CONTIKI_SOURCEFILES += ds1000-sensor.c
all: $(CONTIKI_PROJECT)



include $(CONTIKI)/Makefile.include
